import "./globals.css";

import { Header } from "./(components)/header/Header";

import { Dosis } from "next/font/google";
import { Footer } from "./(components)/footer/Footer";

const dosis = Dosis({
  subsets: ["latin"],
});

export const metadata = {
  title: "Week 2 class-work demo",
  // description: "Generated by create next app",
};

export const link = {
  rel: "icon",
  href: "/favicon.ico",
  sizes: "any",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={dosis.className}>
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
