import "./globals.css";

import { Footer } from "./(components)/footer/Footer";
import { NavBar } from "./(components)/nav-bar/NavBar";

import { Dosis } from "next/font/google";

const dosis = Dosis({
  subsets: ["latin"],
});

export const metadata = {
  title: "week 4 next.js class work",
  // description: "Generated by create next app",
};

export const list = {
  rel: "icon",
  href: "/favicon.ico",
  sizes: "any",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dosis.className}>
        <NavBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
