import type { Metadata } from "next";
import { Dosis } from "next/font/google";
import "./globals.css";
import { Footer } from "./(components)/footer/Footer";
import { NavBar } from "./(components)/nav-bar/NavBar";

const dosis = Dosis({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "react week 5 classwork",
  // description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dosis.className}>
        <NavBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
