import "./globals.css";

import { Dosis } from "next/font/google";

import { NavBar } from "./(components)/navBar/NavBar";

const dosis = Dosis({
  subsets: ["latin"],
});

export const metadata = {
  title: "Week 3 class-work demo",
  // description: "Generated by create next app",
};

export const link = {
  rel: "icon",
  href: "/favicon.ico",
  sizes: "any",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={dosis.className}>
      <body>
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
